environments:

 local:
   scheme: http
   host: localhost
   port: 80
   
 development:  
   scheme: http
   host: localhost
   port: 80
   
 test:  
   scheme: http
   host: localhost
   port: 80
   
 production:  
   scheme: http
   host: 127.0.0.1
   port: 80